import { ArrowUpLeft, Check, ChevronDown, FileText, Layers3, Search, Sparkles } from 'lucide-react';
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

export function Button({ children, variant = 'primary', onClick, type = 'button' }: { children: React.ReactNode; variant?: 'primary' | 'dark' | 'ghost' | 'text'; onClick?: () => void; type?: 'button' | 'submit' }) { return <button type={type} className={`btn ${variant}`} onClick={onClick}>{children}</button>; }
export function Eyebrow({ children, dark = false }: { children: React.ReactNode; dark?: boolean }) { return <div className={`eyebrow ${dark ? 'dark' : ''}`}><span />{children}</div>; }
export function MetricCard({ metric }: { metric: string[] }) { return <div className="metric-card"><span>{metric[1]}</span><strong>{metric[0]}</strong><small>{metric[2]}</small></div>; }
export function SectionHeading({ eyebrow, title, action, onAction }: { eyebrow?: string; title: string; action?: string; onAction?: () => void }) { return <div className="section-heading"><div>{eyebrow && <Eyebrow dark>{eyebrow}</Eyebrow>}<h2>{title}</h2></div>{action && <Button variant="text" onClick={onAction}>{action}<ArrowUpLeft size={16} /></Button>}</div>; }
export function Status({ children, tone = 'green' }: { children: React.ReactNode; tone?: 'green' | 'gold' | 'blue' | 'red' }) { return <span className={`status ${tone}`}><i />{children}</span>; }
export function EmptyState({ title, text, action }: { title: string; text: string; action?: string }) { return <div className="empty-state"><div className="empty-icon"><Sparkles size={21} /></div><h3>{title}</h3><p>{text}</p>{action && <Button variant="dark">{action}<ArrowUpLeft size={15} /></Button>}</div>; }
export function ChartCard({ title, subtitle, data }: { title: string; subtitle: string; data: { name: string; value: number }[] }) { return <div className="panel chart-card"><div className="panel-head"><div><h3>{title}</h3><span>{subtitle}</span></div><button className="select">آخر 6 أشهر <ChevronDown size={14} /></button></div><ResponsiveContainer width="100%" height={220}><AreaChart data={data}><defs><linearGradient id="areaFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#1a735e" stopOpacity={.28} /><stop offset="100%" stopColor="#1a735e" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#89958e', fontSize: 11 }} /><YAxis hide /><Tooltip /><Area type="monotone" dataKey="value" stroke="#1a735e" strokeWidth={3} fill="url(#areaFill)" /></AreaChart></ResponsiveContainer></div>; }
export function MapCanvas({ label = 'الخريطة التحليلية', accent = '#5ca17f' }: { label?: string; accent?: string }) { return <div className="map-shell" aria-label={`${label}. خريطة تجريبية تلخص المناطق والنتائج المكانية`}><div className="map-toolbar"><button aria-label="تكبير">＋</button><button aria-label="تصغير">−</button><button aria-label="الطبقات"><Layers3 size={15} /></button></div><div className="map-road road-a" /><div className="map-road road-b" /><div className="map-road road-c" /><div className="map-road road-d" /><div className="map-boundary boundary-a" style={{ borderColor: accent }} /><div className="map-boundary boundary-b" style={{ borderColor: accent }} /><div className="map-point point-a" style={{ background: accent }} /><div className="map-point point-b" style={{ background: accent }} /><div className="map-point point-c" style={{ background: '#b69255' }} /><div className="map-label label-a">منطقة أولوية</div><div className="map-label label-b">فرصة ناشئة</div><div className="map-legend"><span><i style={{ background: accent }} />مرتفع</span><span><i style={{ background: '#b69255' }} />متوسط</span><span><i style={{ background: '#93b5a7' }} />منخفض</span></div><div className="map-note"><MapPinIcon />{label}</div></div>; }
function MapPinIcon() { return <span className="pin-icon" />; }
export function DataTable({ rows, headings = ['العنصر', 'النطاق', 'المالك', 'التحديث', 'الحالة'] }: { rows: string[][]; headings?: string[] }) { return <div className="table-wrap"><table><thead><tr>{headings.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${row[0]}-${index}`}>{row.map((cell, i) => <td key={`${cell}-${i}`}>{i === 0 ? <b>{cell}</b> : i === row.length - 1 ? <Status tone={cell.includes('مراجعة') ? 'gold' : 'green'}>{cell}</Status> : cell}</td>)}</tr>)}</tbody></table></div>; }
export function SearchBox({ placeholder = 'ابحث في استنار' }: { placeholder?: string }) { return <label className="search-box"><Search size={16} /><input placeholder={placeholder} aria-label={placeholder} /></label>; }
export function Recommendation({ title, text, score, accent = '#2a765c', onOpen }: { title: string; text: string; score: string; accent?: string; onOpen?: () => void }) { return <div className="recommendation" style={{ '--accent': accent } as React.CSSProperties}><div className="recommendation-icon"><Sparkles size={19} /></div><Status>توصية موثوقة</Status><h3>{title}</h3><p>{text}</p><div className="recommendation-score"><strong>{score}</strong><span>درجة الملاءمة<br />من 100</span></div><Button variant="dark" onClick={onOpen}>عرض أسباب التوصية <ArrowUpLeft size={15} /></Button></div>; }
export function DetailCard({ title, value, note, icon = <FileText size={18} /> }: { title: string; value: string; note: string; icon?: React.ReactNode }) { return <div className="detail-card"><div className="detail-icon">{icon}</div><span>{title}</span><strong>{value}</strong><small>{note}</small></div>; }
export function CheckList({ items }: { items: string[] }) { return <ul className="check-list">{items.map(item => <li key={item}><span><Check size={12} /></span>{item}</li>)}</ul>; }
