import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity, ArrowUpLeft, BarChart3, Bell, Building2, ChevronDown, CircleHelp, Database, FileText, Globe2, Layers3, LayoutDashboard, Map, Menu, Search, Settings, ShieldCheck, Sparkles, Target, Users, X, Zap} from 'lucide-react';
import {Area,AreaChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import './styles.css';

type Section={id:string;label:string;icon:React.ElementType};
const domains=[
 {id:'business',label:'الأعمال والاستثمار',en:'Business & Investment',icon:Building2,accent:'#b69255',desc:'اكتشف أفضل المواقع والفرص التجارية بثقة أعلى.'},
 {id:'quality',label:'الخدمات وجودة الحياة',en:'Urban Services',icon:Globe2,accent:'#63b69c',desc:'وزّع الخدمات بعدالة، ووجّه أثر المشاريع إلى حيث الحاجة.'},
 {id:'health',label:'الصحة والرعاية',en:'Health & Care',icon:Activity,accent:'#5ca7a1',desc:'افهم فجوات التغطية الصحية وقرّب الرعاية من السكان.'},
 {id:'tourism',label:'السياحة والفعاليات',en:'Tourism & Events',icon:Sparkles,accent:'#c59d65',desc:'خطّط لوجهات وفعاليات تحقق تجربة أفضل للزوار.'},
 {id:'planning',label:'التخطيط والنمو المكاني',en:'Urban Planning',icon:Layers3,accent:'#8ba59b',desc:'استبق ضغط النمو الحضري وحدد الأولويات بعيدة المدى.'}
];
const adminSections:Section[]=[{id:'admin',label:'لوحة التنفيذية',icon:LayoutDashboard},{id:'domain-center',label:'مركز النطاقات',icon:Globe2},{id:'sources',label:'مصادر البيانات',icon:Database},{id:'quality-data',label:'جودة البيانات',icon:ShieldCheck},{id:'layers',label:'الطبقات المكانية',icon:Layers3},{id:'indicators',label:'مكتبة المؤشرات',icon:BarChart3},{id:'models',label:'نماذج القرار',icon:Target},{id:'analyses',label:'التحليلات',icon:Activity},{id:'projects',label:'القرارات والمشاريع',icon:Target},{id:'reports',label:'التقارير',icon:FileText},{id:'maps',label:'الخرائط',icon:Map},{id:'users',label:'المستخدمون والصلاحيات',icon:Users},{id:'entities',label:'الجهات الحكومية',icon:Building2},{id:'sector-owners',label:'ملاك النطاقات',icon:Users},{id:'notifications',label:'الإشعارات',icon:Bell},{id:'audit',label:'سجل التدقيق',icon:FileText},{id:'activity-log',label:'سجل النشاط',icon:Activity},{id:'integrations',label:'التكاملات',icon:Zap},{id:'monitoring',label:'مراقبة المنصة',icon:Activity},{id:'system',label:'تهيئة النظام',icon:Settings},{id:'settings',label:'الإعدادات',icon:Settings},{id:'profile',label:'الملف الشخصي',icon:Users}];
const trend=[{name:'يناير',value:54},{name:'فبراير',value:61},{name:'مارس',value:58},{name:'أبريل',value:72},{name:'مايو',value:79},{name:'يونيو',value:86}];
const stats=[['12','نموذج قرار نشط','+3 هذا الشهر'],['48','تحليل مكتمل','+12% من الشهر الماضي'],['86%','جودة البيانات','مستقرة'],['24','مشروعاً قيد المتابعة','8 عالية الأولوية']];
function App(){const [active,setActive]=useState('home');const [open,setOpen]=useState(false); const current=domains.find(d=>d.id===active); const isAdmin=adminSections.some(s=>s.id===active); return <div className="app">
 <header className="top"><div className="brand"><span className="brand-mark">ا</span><div><b>استنار</b><small>ذكاء القرار المكاني</small></div></div><div className="top-actions"><button className="icon-btn" aria-label="بحث"><Search size={18}/></button><button className="icon-btn" aria-label="الإشعارات"><Bell size={18}/><i/></button><div className="profile"><span>م</span><div><b>محمد العتيبي</b><small>محلل استراتيجي</small></div><ChevronDown size={15}/></div></div></header>
 <aside className={open?'side open':'side'}><button className="close" onClick={()=>setOpen(false)}><X/></button><div className="side-label">مساحة العمل</div><Nav icon={LayoutDashboard} label="المنصة التنفيذية" active={active==='home'} onClick={()=>setActive('home')}/><Nav icon={Map} label="استكشف المدينة" active={active==='explore'} onClick={()=>setActive('explore')}/><Nav icon={Target} label="مركز القرار" active={active==='decisions'} onClick={()=>setActive('decisions')}/><div className="side-label">النطاقات</div>{domains.map(d=><Nav key={d.id} icon={d.icon} label={d.label} active={active===d.id} onClick={()=>setActive(d.id)} accent={d.accent}/>)}<div className="side-label">الإدارة</div>{adminSections.map(s=><Nav key={s.id} icon={s.icon} label={s.label} active={active===s.id} onClick={()=>setActive(s.id)}/>)}</aside>
 <main><div className="mobile-bar"><button className="icon-btn" onClick={()=>setOpen(true)}><Menu/></button><span>استنار</span></div>{active==='home'?<Home setActive={setActive}/>:isAdmin?<Admin active={active}/>:active==='explore'||active==='decisions'?<Shared active={active} setActive={setActive}/>:<Domain domain={current!} setActive={setActive}/>}</main>
 </div>}
function Nav({icon:Icon,label,active,onClick,accent}:any){return <button className={active?'nav active':'nav'} onClick={onClick} style={active&&accent?({'--accent':accent} as React.CSSProperties):undefined}><Icon size={18}/><span>{label}</span>{active&&<ArrowUpLeft size={14}/>}</button>}
function Shared({active,setActive}:any){const decision=active==='decisions';return <section className="content shared-page"><div className="page-title"><div><div className="eyebrow dark"><span/>{decision?'مركز القرار':'استكشف المدينة'}</div><h1>{decision?'قرارات أوضح، من مكان واحد':'لوحة المدينة الموحدة'}</h1><p>{decision?'تابع التحليلات والتوصيات وحوّل الرؤية إلى خطوات قابلة للمتابعة.':'استكشف المؤشرات المكانية والقطاعية في طبقة واحدة، ثم انتقل إلى التحليل الذي تحتاجه.'}</p></div><button className="btn primary" onClick={()=>setActive('business')}>إنشاء تحليل <ArrowUpLeft size={16}/></button></div><div className="dashboard-grid"><div className="panel map-panel"><div className="panel-head"><div><h3>{decision?'التحليلات النشطة':'الخريطة الموحدة'}</h3><span>بيانات استنار · محدثة قبل 14 دقيقة</span></div><button className="select"><Layers3 size={14}/> الطبقات</button></div><div className="mock-map"><div className="map-road r1"/><div className="map-road r2"/><div className="map-road r3"/><div className="map-zone z1">خدمات</div><div className="map-zone z2">نمو</div><div className="map-pin p1"/><div className="map-pin p2"/></div></div><div className="panel insight-panel"><div className="insight-icon"><Sparkles size={20}/></div><small>ملخص استنار</small><h3>{decision?'لديك 3 توصيات تنتظر المراجعة':'تظهر 4 إشارات تستحق الاستكشاف اليوم'}</h3><p>يمكنك فتح التفاصيل ومقارنة المواقع والاحتفاظ بالنتائج في مساحتك.</p><button className="btn dark" onClick={()=>setActive('quality')}>استكشف نطاقاً <ArrowUpLeft size={15}/></button></div></div><div className="domain-grid shared-cards">{[['تحليل فجوات الخدمات','جودة الحياة','6 مناطق ذات أولوية'],['فرص تجارية واعدة','الأعمال والاستثمار','18 موقعاً مرشحاً'],['ضغط النمو الحضري','التخطيط والنمو','توقعات الربع القادم']].map((x,i)=><div className="panel" key={x[0]}><small className="muted">{x[1]}</small><h3>{x[0]}</h3><p className="muted">{x[2]}</p><button className="text-btn">فتح التحليل <ArrowUpLeft size={14}/></button></div>)}</div></section>}
function Home({setActive}:any){return <><section className="hero"><div className="grid-lines"/><div className="hero-content"><div className="eyebrow"><span/>منصة حكومية موحّدة</div><h1>من بيانات المدينة<br/><em>إلى قرار أوضح</em></h1><p>استنار يحوّل البيانات المكانية والقطاعية إلى توصيات قابلة للتفسير، تساعد الجهات والمستثمرين على معرفة أين يبدأ الأثر.</p><div className="hero-actions"><button className="btn primary" onClick={()=>setActive('explore')}>ابدأ استكشاف المدينة <ArrowUpLeft size={17}/></button><button className="btn ghost" onClick={()=>setActive('decisions')}>مركز القرار</button></div></div><div className="orbit"><div className="orbit-core"><span>ESTNAR</span><b>قرار</b></div><div className="orbit-node n1">بيانات</div><div className="orbit-node n2">موقع</div><div className="orbit-node n3">أثر</div></div></section><section className="content"><div className="section-head"><div><div className="eyebrow dark"><span/>نظرة تنفيذية</div><h2>صورة المدينة في لحظة</h2></div><button className="text-btn" onClick={()=>setActive('reports')}>عرض التقرير التنفيذي <ArrowUpLeft size={16}/></button></div><div className="stat-grid">{stats.map(s=><div className="stat-card" key={s[1]}><small>{s[1]}</small><strong>{s[0]}</strong><span>{s[2]}</span></div>)}</div><div className="dashboard-grid"><div className="panel chart-panel"><div className="panel-head"><div><h3>مؤشر النشاط والقرارات</h3><span>آخر ستة أشهر</span></div><button className="select">كل النطاقات <ChevronDown size={14}/></button></div><ResponsiveContainer width="100%" height={220}><AreaChart data={trend}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#1a735e" stopOpacity={.3}/><stop offset="100%" stopColor="#1a735e" stopOpacity={0}/></linearGradient></defs><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill:'#89958e',fontSize:11}}/><YAxis hide/><Tooltip/><Area type="monotone" dataKey="value" stroke="#1a735e" strokeWidth={3} fill="url(#fill)"/></AreaChart></ResponsiveContainer></div><div className="panel insight-panel"><div className="insight-icon"><Sparkles size={20}/></div><small>إشارة استنار</small><h3>الضغط على الخدمات يرتفع في الشمال الشرقي</h3><p>تظهر مؤشرات النمو السكاني فجوة متوقعة في الخدمات خلال الربع القادم.</p><button className="btn dark" onClick={()=>setActive('planning')}>استعرض التحليل <ArrowUpLeft size={16}/></button></div></div><div className="section-head domains-head"><div><div className="eyebrow dark"><span/>النطاقات المتخصصة</div><h2>قرارك يبدأ من السياق الصحيح</h2></div></div><div className="domain-grid">{domains.map(d=><button className="domain-card" key={d.id} onClick={()=>setActive(d.id)} style={{'--accent':d.accent} as any}><div className="domain-top"><span className="domain-icon"><d.icon size={21}/></span><ArrowUpLeft size={18}/></div><small>{d.en}</small><h3>{d.label}</h3><p>{d.desc}</p><div className="domain-foot">استكشف النطاق <ArrowUpLeft size={15}/></div></button>)}</div></section></>}
function Domain({domain,setActive}:any){return <section className="content domain-page"><div className="domain-banner" style={{'--accent':domain.accent} as React.CSSProperties}><div><div className="eyebrow"><span/>نطاق استنار · {domain.en}</div><h1>{domain.label}</h1><p>{domain.desc}</p><button className="btn primary" onClick={()=>setActive('explore')}>ابدأ التحليل <ArrowUpLeft size={17}/></button></div><div className="domain-ring"><domain.icon size={54}/><span>قرار<br/>مدعوم</span></div></div><div className="section-head"><div><div className="eyebrow dark"><span/>ملخص النطاق</div><h2>ماذا يحدث الآن؟</h2></div><button className="text-btn">تنزيل التقرير <FileText size={16}/></button></div><div className="stat-grid">{[['72%','تغطية المؤشرات','ثقة مرتفعة'],['18','موقعاً مرشحاً','تحتاج مراجعة'],['6','فجوات ذات أولوية','-2 هذا الأسبوع'],['91','درجة الجاهزية','من أصل 100']].map(s=><div className="stat-card" key={s[1]}><small>{s[1]}</small><strong>{s[0]}</strong><span>{s[2]}</span></div>)}</div><div className="analysis-grid"><div className="panel map-panel"><div className="panel-head"><div><h3>الخريطة التحليلية</h3><span>المدينة · آخر تحديث قبل 14 دقيقة</span></div><button className="select"><Layers3 size={14}/> الطبقات</button></div><div className="mock-map"><div className="map-road r1"/><div className="map-road r2"/><div className="map-road r3"/><div className="map-zone z1">أولوية عالية</div><div className="map-zone z2">فرصة ناشئة</div><div className="map-pin p1"/><div className="map-pin p2"/><div className="map-legend"><span/><span/><span/></div></div></div><div className="panel recommendation"><div className="insight-icon"><Zap size={19}/></div><small>التوصية الأولى</small><h3>حي النقرة · موقع واعد</h3><div className="score"><b>87</b><span>/ 100<br/>درجة الملاءمة</span></div><p>يعتمد التقييم على الطلب، إمكانية الوصول، وتوازن العرض في المنطقة.</p><button className="btn dark">عرض أسباب التوصية <ArrowUpLeft size={15}/></button></div></div><div className="panel table-panel"><div className="panel-head"><div><h3>المواقع الأعلى ترتيباً</h3><span>قائمة قابلة للمقارنة</span></div><button className="text-btn">عرض الكل <ArrowUpLeft size={15}/></button></div><table><thead><tr><th>الموقع</th><th>الملاءمة</th><th>الثقة</th><th>الحالة</th></tr></thead><tbody>{[['حي النقرة','87','مرتفعة','موصى به'],['حي المطار','79','مرتفعة','قيد المراجعة'],['شارع الملك عبدالعزيز','74','متوسطة','بديل مناسب']].map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td><strong className="green-text">{r[1]}</strong></td><td>{r[2]}</td><td><span className="badge">{r[3]}</span></td></tr>)}</tbody></table></div></section>}
function Admin({active}:any){const title=adminSections.find(s=>s.id===active)?.label||'الإدارة';return <section className="content admin-page"><div className="page-title"><div><div className="eyebrow dark"><span/>إدارة المنصة</div><h1>{title}</h1><p>تحكم مركزي في البيانات والمؤشرات ونماذج القرار عبر جميع نطاقات استنار.</p></div><button className="btn primary"><span>＋</span> إضافة جديد</button></div><div className="admin-summary"><div><ShieldCheck size={20}/><b>حالة المنصة</b><strong>مستقرة</strong></div><div><Database size={20}/><b>مصادر متصلة</b><strong>24 / 26</strong></div><div><Activity size={20}/><b>آخر مزامنة</b><strong>قبل 14 دقيقة</strong></div><div><Users size={20}/><b>مستخدمون نشطون</b><strong>186</strong></div></div><div className="panel table-panel admin-table"><div className="panel-head"><div><h3>سجل العمليات الأخيرة</h3><span>متابعة النشاط التشغيلي والبيانات</span></div><div className="table-tools"><div className="search"><Search size={15}/><input placeholder="ابحث في السجلات"/></div><button className="select">تصفية <ChevronDown size={14}/></button></div></div><table><thead><tr><th>العنصر</th><th>النطاق</th><th>المالك</th><th>آخر تحديث</th><th>الحالة</th></tr></thead><tbody>{[['نموذج أولوية الحدائق','جودة الحياة','فريق التخطيط','منذ ساعتين','نشط'],['مصادر التراخيص التجارية','الأعمال والاستثمار','مركز البيانات','منذ 4 ساعات','محدّث'],['طبقة حدود الأحياء','التخطيط والنمو','نظم المعلومات','أمس','مراجعة مطلوبة'],['تقرير التغطية الصحية','الصحة والرعاية','وزارة الصحة','أمس','جاهز'],['مؤشر جاهزية الفعاليات','السياحة والفعاليات','فريق السياحة','منذ 3 أيام','نشط']].map(r=><tr key={r[0]}><td><b>{r[0]}</b></td><td>{r[1]}</td><td>{r[2]}</td><td>{r[3]}</td><td><span className="badge">{r[4]}</span></td></tr>)}</tbody></table></div></section>}
createRoot(document.getElementById('root')!).render(<App/>);
